filter f_aliaserd {
    program("aliaserd");
};

destination d_aliaserd {
    file("/var/log/aliaser/aliaser.log"
        create-dirs(yes));
};

log {
    source(s_local);
    filter(f_aliaserd);
    destination(d_aliaserd);
};
