[start]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py start
parameters:
type:script
message:starting aliaser daemon

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py stop
parameters:
type:script
message:stopping aliaser daemon

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py restart
parameters:
type:script
message:restarting aliaser daemon
description:Restart Aliaser

[status]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py status
parameters:
type:script_output
message:show aliaser daemon status

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py reconfigure
parameters:
type:script_output
message:reconfigure aliaser daemon

[refresh]
command:/usr/local/opnsense/scripts/OPNsense/Aliaser/aliaserd.py refresh
parameters:%s
type:script_output
message:force refresh watcher %s
